#!/bin/bash

docker build --build-arg MONGO_VERSION=4.2.11 \
             --build-arg ES_VERSION=6.8.13 \
             --build-arg GRAYLOG_VERSION=4.0.1 \
             --build-arg GRAFANA_VERSION=7.3.7 \
             --tag logserver .
