#!/bin/bash

docker build --build-arg MONGO_VERSION=4.2.8 \
             --build-arg ES_VERSION=6.8.10 \
             --build-arg GRAYLOG_VERSION=3.3.2 \
             --build-arg GRAFANA_VERSION=7.0.6 \
             --tag logserver .
